name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [10]
        dart-version: [stable, dev]
        # for now, code-version will mirror dart-version to reduce number of bots
        # code-version: [stable] #, insiders]
        bot: [flutter_debug, flutter_debug_chrome, flutter_test_debug, dart_web_debug, flutter_repo, dart_debug, dart, flutter, misc]
        include:
          - dart-version: stable
            flutter-version: beta
            code-version: stable
          - dart-version: dev
            flutter-version: dev
            code-version: insiders

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
    - name: Setup Flutter ${{ matrix.flutter-version }}
      id: flutter
      if: "!startsWith(matrix.bot, 'dart')"
      uses: DanTup/gh-actions/setup-flutter@master
      with:
          channel: ${{ matrix.flutter-version }}
